# Generated by Django 5.1.2 on 2025-09-24 06:18

import django.db.models.deletion
import django.utils.timezone
import invoices.models
import mptt.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم التجاري عربي')),
                ('en_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم التجاري بالإنجليزي')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الجوال')),
                ('fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الفاكس')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان (سطر 1)')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='المدينة')),
                ('postal_code', models.CharField(blank=True, max_length=9, null=True, verbose_name='الرمز البريدي')),
                ('country', models.CharField(blank=True, default='المملكة العربية السعودية', max_length=100, null=True, verbose_name='الدولة')),
                ('vat_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم الضريبي')),
                ('cr_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم السجل التجاري')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=15.0, max_digits=4, verbose_name='نسبة الضريبة (%)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='شعار المنشأة')),
            ],
            options={
                'verbose_name': 'إعدادات المنشأة',
                'verbose_name_plural': 'إعدادات المنشآت',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم العميل')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('address_line', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان الشارع')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='المدينة')),
                ('country', models.CharField(blank=True, default='المملكة العربية السعودية', max_length=100, null=True, verbose_name='البلد')),
                ('vat_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='الرقم الضريبي (إن وجد)')),
                ('cr_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم السجل التجاري (إن وجد)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='حد الائتمان')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'عملاء',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=50, unique=True, verbose_name='الاسم العربي')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='الاسم الإنجليزي')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'طريقة دفع',
                'verbose_name_plural': 'طرق الدفع',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الصنف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'صنف المنتج',
                'verbose_name_plural': 'أصناف المنتجات',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المورد')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('address_line', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان الشارع')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='المدينة')),
                ('country', models.CharField(blank=True, default='المملكة العربية السعودية', max_length=100, null=True, verbose_name='البلد')),
                ('vat_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='الرقم الضريبي (إن وجد)')),
                ('cr_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم السجل التجاري (إن وجد)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
            ],
            options={
                'verbose_name': 'مورد',
                'verbose_name_plural': 'الموردون',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الوحدة الأساسية')),
                ('abbreviation', models.CharField(max_length=20, verbose_name='التمييز')),
                ('template', models.CharField(help_text='مثال: الوزن', max_length=50, verbose_name='القالب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'وحدة',
                'verbose_name_plural': 'الوحدات',
            },
        ),
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='رمز الحساب')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الحساب')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('account_type', models.CharField(choices=[('asset', 'أصول'), ('liability', 'خصوم'), ('equity', 'حقوق ملكية'), ('income', 'إيرادات'), ('expense', 'مصروفات')], max_length=50, verbose_name='نوع الحساب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='الرصيد')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='invoices.chartofaccount', verbose_name='الحساب الأب')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'شجرة الحسابات',
            },
        ),
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='رقم السند')),
                ('payment_type', models.CharField(choices=[('receipt', 'سند قبض من العميل'), ('refund', 'سند رد مبلغ للعميل')], default='receipt', max_length=20, verbose_name='نوع الدفعة')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='مبلغ الدفعة')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الدفعة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('is_posted', models.BooleanField(default=False, verbose_name='تم إنشاء القيد؟')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoices.customer', verbose_name='العميل')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_payments', to='invoices.paymentmethod', verbose_name='طريقة الدفع')),
            ],
            options={
                'verbose_name': 'دفعة عميل',
                'verbose_name_plural': 'دفعات العملاء',
            },
        ),
        migrations.CreateModel(
            name='CustomerLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('description', models.CharField(max_length=255, verbose_name='الوصف')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='مدين')),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='دائن')),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الرصيد بعد الحركة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.customer', verbose_name='العميل')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='invoices.customerpayment')),
            ],
            options={
                'verbose_name': 'حركة دفتر العميل',
                'verbose_name_plural': 'دفتر مساعد العملاء',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('sales', 'فاتورة مبيعات'), ('sales_return', 'مرتجع مبيعات'), ('purchase', 'فاتورة مشتريات'), ('purchase_return', 'مرتجع مشتريات')], default='sales', max_length=20, verbose_name='نوع الفاتورة')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الفاتورة')),
                ('status', models.CharField(choices=[('unpaid', 'غير مدفوعة'), ('paid', 'مدفوعة'), ('cancelled', 'ملغاة')], default='unpaid', max_length=20, verbose_name='حالة الفاتورة')),
                ('invoice_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ ووقت الفاتورة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('return_reason', models.TextField(blank=True, default='0', null=True, verbose_name='سبب المرتجع')),
                ('subtotal_before_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='الإجمالي قبل الخصم')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='نسبة الخصم %')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='قيمة الخصم')),
                ('subtotal_before_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='المجموع قبل الضريبة')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, verbose_name='نسبة الضريبة')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='قيمة الضريبة')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='الصافي')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='كود QR')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('is_posted', models.BooleanField(default=False, verbose_name='تم إنشاء القيد؟')),
                ('company', models.ForeignKey(default=invoices.models.get_default_company, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.companysettings', verbose_name='الشركة')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.customer', verbose_name='العميل')),
                ('original_invoice', models.ForeignKey(blank=True, help_text='لفواتير المرتجعات', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='invoices.invoice', verbose_name='الفاتورة الأصلية')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.paymentmethod', verbose_name='طريقة الدفع')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'الفواتير',
                'unique_together': {('invoice_type', 'invoice_number')},
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ القيد')),
                ('description', models.TextField(verbose_name='وصف القيد')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='مدين')),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='دائن')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.chartofaccount', verbose_name='الحساب')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='invoices.journalentry')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255, verbose_name='اسم المنتج بالعربي')),
                ('serial_number', models.CharField(max_length=255, unique=True, verbose_name='الرقم التسلسلي')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('stock', models.PositiveIntegerField(blank=True, default=999999999, verbose_name='الكمية المتاحة')),
                ('low_stock_threshold', models.PositiveIntegerField(blank=True, default=10, null=True, verbose_name='حد التنبيه')),
                ('inventory_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_products', to='invoices.chartofaccount', verbose_name='حساب المخزون')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='invoices.productcategory', verbose_name='الصنف')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.unit', verbose_name='وحدة القياس')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
            },
        ),
        migrations.CreateModel(
            name='SupplierLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('description', models.CharField(max_length=255, verbose_name='الوصف')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='مدين')),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='دائن')),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='الرصيد بعد الحركة')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'حركة دفتر المورد',
                'verbose_name_plural': 'دفتر مساعد الموردين',
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='رقم السند')),
                ('payment_type', models.CharField(choices=[('payment', 'سند صرف للمورد'), ('refund', 'المورد يرد مبلغ')], default='payment', max_length=20, verbose_name='نوع الدفعة')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='مبلغ الدفعة')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الدفعة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('is_posted', models.BooleanField(default=False, verbose_name='تم إنشاء القيد؟')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments', to='invoices.paymentmethod', verbose_name='طريقة الدفع')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoices.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'دفعة مورد',
                'verbose_name_plural': 'دفعات الموردين',
            },
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('larger_unit_name', models.CharField(max_length=100, verbose_name='اسم الوحدة الأكبر')),
                ('larger_unit_abbreviation', models.CharField(max_length=20, verbose_name='التمييز')),
                ('conversion_factor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='معامل التحويل')),
                ('base_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='invoices.unit', verbose_name='الوحدة الأساسية')),
            ],
            options={
                'verbose_name': 'تحويل وحدة',
                'verbose_name_plural': 'تحويلات الوحدات',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر لكل وحدة')),
                ('total_before_tax', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='المجموع قبل الضريبة')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=15, max_digits=5, verbose_name='نسبة الضريبة')),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='المجموع النهائي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='invoices.invoice', verbose_name='الفاتورة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoices.product', verbose_name='المنتج')),
                ('base_unit', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.unit', verbose_name='الوحدة الأساسية')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.unitconversion', verbose_name='الوحدة المختارة')),
            ],
            options={
                'verbose_name': 'عنصر الفاتورة',
                'verbose_name_plural': 'عناصر الفاتورة',
            },
        ),
    ]
