# Generated by Django 5.1.2 on 2025-09-24 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'verbose_name': 'بند فاتورة', 'verbose_name_plural': 'بنود الفواتير'},
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='base_unit',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='total',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='base_quantity_calculated',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='الكمية بالوحدة الأساسية (محسوبة)'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='invoices.invoice', verbose_name='الفاتورة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='هذا هو سعر الوحدة الأصغر دائماً (مثل الياردة أو الحبة)', max_digits=10, verbose_name='سعر الوحدة الأساسية (إفرادي)'),
        ),
    ]
