# Generated by Django 5.1.2 on 2026-03-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_companysettings_bank_name_companysettings_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان الحي'),
        ),
    ]
