# Generated by Django 5.1.2 on 2026-03-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_branch_invoice_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='branch',
            field=models.CharField(default=0, max_length=255, verbose_name='اسم الفرع'),
            preserve_default=False,
        ),
    ]
